{% set name = "eiquadprog" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b71bff3058b102831da092f9ffc69713073285e751d8e8819647893b0af46613

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
  host:
    - eigen
    - libboost-devel
  run:
    - eigen
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: http://github.com/stack-of-tasks/eiquadprog
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: C++ implementations of the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of a dual method
  dev_url: https://github.com/stack-of-tasks/eiquadprog

extra:
  recipe-maintainers:
    - jcarpent
    - EtienneAr
