{% set name = "eiquadprog" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4ac25a0236dd08f5d5f1890a33ca78a9c8a5808f7e34d0269d942fa9320036d

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
  host:
    - eigen
    - libboost-devel
  run:
    - eigen
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: http://github.com/stack-of-tasks/eiquadprog
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: C++ implementations of the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of a dual method
  dev_url: https://github.com/stack-of-tasks/eiquadprog

extra:
  recipe-maintainers:
    - jcarpent
    - EtienneAr
