{% set name = "eiquadprog" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9dab0ae734a6c7a72b63992cbe9ad96901349c000a43eed0e5ed2700443f846
  patches:
    - win_support.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - eigen
  run:
    - eigen
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}  # [not osx or not arm64] 

about:
  home: http://github.com/stack-of-tasks/eiquadprog
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: C++ implementations of the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of a dual method
  dev_url: https://github.com/stack-of-tasks/eiquadprog

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - EtienneAr
