{% set name = "eiquadprog" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41f317803933d42a2228b041e7f94d75fb4239449a2e291f404ab18c82622cd4
  patches:
    - win_support.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - eigen
  run:
    - eigen
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}  # [not osx or not arm64] 

about:
  home: http://github.com/stack-of-tasks/eiquadprog
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: C++ implementations of the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of a dual method
  dev_url: https://github.com/stack-of-tasks/eiquadprog

extra:
  recipe-maintainers:
    - jcarpent
    - EtienneAr
